# Your theme's name must begin with Plastic, e.g. Plastic Horses
name: Plastic

# Your theme must provide hex values for these named colours. They are used for
# the terminal. You can either use these colours for your syntax theme or append
# some more of your own.
colours:
  - blue: '#61AFEF'
  - bright_blue: '#007FFF'
  - cyan: '#56B6C2'
  - bright_cyan: '#08E8DE'
  - green: '#98C379'
  - bright_green: '#66FF00'
  - magenta: '#B57EDC'
  - bright_magenta: '#8B00FF'
  - red: '#E06C75'
  - bright_red: '#E34234'
  - yellow: '#D19A66'
  - bright_yellow: '#E5C07B'

# This is where you define a colour to each group of syntax. If you leave as
# null, the default Plastic colour will be used.
syntax:
  - functions: yellow # function names, and React props.
  - keywords: red # import, export, return etc.
  - primitives: cyan # numbers, booleans (not strings)
  - punctuation: null # brackets, quotes etc.
  - storage: blue # const, var, class etc. and React JSX component tag
  - strings: green # anything in quotes
  - tags: bright_yellow # html tags
